### ISSUE TITLE
"Built with 47deg/sbt-microsites"

### ISSUE THREAD

**Issue by raulraja** [47deg/sbt-microsites#115]
Needed for library adoption we should include footer text and links or badge "Built with github.com/47deg/org" or similar

**Comment by MaureenElsberry** [comment]
This has been completed for org - we ended up with the footer being configured as default to 

![8e87c6ee-d8c3-11e6-888d-ddc8a5c2ea94](https://cloud.githubusercontent.com/assets/17556002/22036464/84a00f9a-dca8-11e6-8f7a-783dc90e9690.png)

i think in this case adding the 47 Degrees is too long considering the long library name - so I would say 

Copyright 2017 __________ - Built with sbt-microsites

@juanpedromoreno - can be seen here: https://github.com/47deg/org/pull/36

**Comment by MaureenElsberry** [comment]
Did this get resolved @juanpedromoreno @raulraja?  Or still open?

**Comment by juanpedromoreno** [comment]
I've just seen your last message, sorry for the late response. It didn't get resolved yet.

**Comment by MaureenElsberry** [comment]
no worries - just making sure it wasn't waiting to be closed out.
