### ISSUE TITLE
Support multiple versions

### ISSUE THREAD

**Issue by akkie** [47deg/sbt-microsites#116]
Currently it seems that `sbt-microsites` is built only from master branch. There should be a mechanism to support multiple versions that can be selected by a dropdown or similar navigation element. Versions could be generated from git tags or from configuration file which maps versions to git branches or commits.

**Comment by juanpedromoreno** [comment]
Not sure if this project https://github.com/epoberezkin/gh-pages-generator is the way to go.

**Comment by kailuowang** [comment]
👍 on this. A single reference to an unreleased API would prevent the whole website from being updated, which is the current situation at cats.
