### ISSUE TITLE
Kazari integration with new evaluation work

### ISSUE THREAD

**Issue by jdesiloniz** [47deg/sbt-microsites#118]
Some issues in the remote evaluator surfaced while developing the Kazari plugin. This ticket covers the remaining work to make Kazari available once the remote evaluator is ready to support it.

**Comment by jdesiloniz** [comment]
The current work is available in https://github.com/47deg/sbt-microsites/tree/kazari-integration

**Comment by raulraja** [comment]
This works needs to be adapted to consume the new endpoints once https://github.com/scala-exercises/evaluator/issues/47 is completed

**Comment by juanpedromoreno** [comment]
Done! thanks @jdesiloniz
