### ISSUE TITLE
Configurable hosting

### ISSUE THREAD

**Issue by cranst0n** [47deg/sbt-microsites#123]
It would be nice, for certain environments, to be able to configure the microsite so that the __View On__ links could point to a different URL. [This](https://github.com/47deg/sbt-microsites/blob/36b56b3bf538233100eb5512188c33526b3f45e0/src/main/scala/microsites/layouts/HomeLayout.scala#L56) assumes the project is hosted on Github but maybe you would like to to point to something like: `http://myInternalServer/git/projects/user/projectname`.

A few instances:

- `Github` header link
- `View on Github` jumbotron button
- `View on Github` footer link

**Comment by raulraja** [comment]
@cranst0n Makes sense. If you want to contribute a PR we can get this addressed as soon as ready otherwise we will consider it for the upcoming release when we have some free OS cycles. Cheers and thanks!

**Comment by juanpedromoreno** [comment]
Closed by #124
