### ISSUE TITLE
Not a git repository error

### ISSUE THREAD

**Issue by lewismj** [47deg/sbt-microsites#146]
Hi,
I can run sbt makeMicrosite locally without any issues - thank you btw. Site looks great.
I have setup my gh_pages branch as per the sbt ghpages plugin.

When I try to run publishMicrosite, I run into this error:

[info]  Auto-regeneration: disabled. Use --watch to enable.
[error] fatal: Not a git repository (or any of the parent directories): .git
java.lang.RuntimeException: Nonzero exit code (128) running git.
	at scala.sys.package$.error(package.scala:27)
	at scala.Predef$.error(Predef.scala:142)

Anyone know what the issue might be?

**Comment by lewismj** [comment]
n.b. the .git folder obviously exists!

**Comment by lewismj** [comment]
resolved, just had to re-clone the repo.

**Comment by joan38** [comment]
Have the same issue and recloning didn't help.

**Comment by joan38** [comment]
Resolved by removing `~/.sbt/ghpages/xxxx`.
See: https://github.com/sbt/sbt-ghpages/issues/14#issuecomment-147653145
