### ISSUE TITLE
Add support for scalatex

### ISSUE THREAD

**Issue by raulraja** [47deg/sbt-microsites#154]
[Scalatex](https://github.com/lihaoyi/Scalatex) is very good alternative to markdown that can be used in addition to `tut` for users that would rather have a typed layer over plain markdown/html  in Scala. It should be possible to configure scalatex as an alternative html generator producing docs that get included in the final site and that look identical to those generated from `markdown -> tut` and finally rendered by sbt-microsite in the jekyll templating structure.

**Comment by juanpedromoreno** [comment]
Scalatex has been deprecated. Let's close this.
