### ISSUE TITLE
micrositeExtraMdFiles copies files in to the tut dir

### ISSUE THREAD

**Issue by Jacoby6000** [47deg/sbt-microsites#194]
I think copying the `.md` files in to the `tut` sources dir should be opt-in (or there should be a way to opt-out). If they're including extra markdown sources that are not in the `tut` directory, there is probably a reason that they are not there.

**Comment by juanpedromoreno** [comment]
I see your point and it makes sense to me. This setting was implemented for some specific use cases that not always match with the project needs.

In the meantime, until we don't find a better solution, you could prevent having those extra markdown sources in your `tut` directory adding them to your `.gitignore` file.

**Comment by Jacoby6000** [comment]
I had considered using a gitignore, but that's really not convenient, especially if you're doing some fancy stuff to find the markdown files specifically so that other people don't have to manually do things. 

My temporary solution is to have a task that runs `makeMicrosite` and then deletes the new tut sources after.
