### ISSUE TITLE
Create UI resources for the sbt-microsites microsite

### ISSUE THREAD

**Issue by juanpedromoreno** [47deg/sbt-microsites#20]
We are using this plugin to generate its microsite. At this moment, we are using the default styles, images and resources provided for the plugin. This is the result:

https://47deg.github.io/sbt-microsites/

We should:
- Create better default styles and resources for the plugin, locating them at https://github.com/47deg/sbt-microsites/tree/master/src/main/resources . Color palette by default: https://github.com/47deg/sbt-microsites/blob/master/src/main/scala/microsites/MicrositesPlugin.scala#L72
- Create the resources for the `sbt-microsites` microsite. We can put everything under this path https://github.com/47deg/sbt-microsites/tree/master/docs/src/main/resources/microsite

Both previous tasks might be the same if you consider it. @israelperezglez ^^

**Comment by juanpedromoreno** [comment]
@raulraja @israelperezglez We should finish this task soon. It's blocked from more than 1 month and I think not much left to finish it. Let's find a couple of hours to finish it if it looks good to you ;)

**Comment by raulraja** [comment]
Ok, let's discuss priorities

**Comment by israelperezglez** [comment]
@raulraja @raulraja I am working in the"code compile" for sbt microsite. This task is the next in the priority list.
