### ISSUE TITLE
sbt-microsites connects to window server on OS X

### ISSUE THREAD

**Issue by tpolecat** [47deg/sbt-microsites#208]
When I do `makeMicrosite` the JVM connects to the window server, which means a generic Java icon called "Boot" appears on the task bar, and if I'm in a fullscreen window when I do this it slides me over to another desktop. Not a big deal, but you can fix it by adding

```scala
System.setProperty("java.awt.headless", "true")
```

before you do whatever it is that's initializing AWT. You might want it to be a setting in case someone actually wants to be able to pop up windows when their doc is compiling.

**Comment by yannbolliger** [comment]
This is still present.
