### ISSUE TITLE
Cross publish to sbt 1.0

### ISSUE THREAD

**Issue by julien-lafont** [47deg/sbt-microsites#211]
It would be nice if sbt-microsite where available for sbt 1.0.

Current state of dependant sbt-plugins:
 - [x] sbt-ghpages https://github.com/sbt/sbt-ghpages/issues/36
 - [x] sbt-site https://github.com/sbt/sbt-site/issues/105
 - [x] tut-plugin https://github.com/tpolecat/tut/commit/43a0f2396fbff61f67834facb13632cac0094611
 - [x] sbt-org-policies https://github.com/47deg/sbt-org-policies/issues/412

**Comment by eaplatanios** [comment]
Is there any update on the status of this?
