### ISSUE TITLE
Option to disable Kazari

### ISSUE THREAD

**Issue by muuki88** [47deg/sbt-microsites#222]
Hi,

The kazari implementation is currently very huge (#62) and has a rendering issue.
A checkbox at the bottom the page is always displayed (e.g. https://typelevel.org/cats/).

It would be nice to disable kazari if you don't make any use of it.

**Comment by juanpedromoreno** [comment]
@jdesiloniz @dominv Is there any way to achieve it?

**Comment by dominv** [comment]
I'm working to add on a micrositeKazariEnabled setting that I believe can be useful to this end
