### ISSUE TITLE
publish v0.7.13?

### ISSUE THREAD

**Issue by SethTisue** [47deg/sbt-microsites#248]
it would be nice to have a release with the #247 fix

my own context for wanting it is https://github.com/scala/community-builds/pull/645

**Comment by suhasgaddam** [comment]
Should the `SettingKey`s in https://github.com/47deg/sbt-microsites/blob/master/project/KazariBuild.scala also be changed to `settingKey`?

**Comment by SethTisue** [comment]
@suhasgaddam they _could_, but I don't think it matters. the bad code that #247 fixed was using big-S-`SettingKey` but only passing one string. it's fine to use big-S-`SettingKey` as long as you pass two strings (the key name & the description)

**Comment by juanpedromoreno** [comment]
@SethTisue Done! https://github.com/47deg/sbt-microsites/pull/249

@suhasgaddam I did the change for the sake of consistency.
