### ISSUE TITLE
micrositeDocumentationUrl and micrositeHompage with non-empty path 

### ISSUE THREAD

**Issue by BenFradet** [47deg/sbt-microsites#251]
The top-right documentation link for cats is broken: https://typelevel.org/cats, as it links to https://typelevel.org/api/cats/index.html instead of https://typelevel.org/cats/api/cats/index.html.

I believe the issues lies with https://github.com/47deg/sbt-microsites/blob/cddebf121135347fc68b50b6cebbc5fe1b0ff91c/src/main/scala/microsites/layouts/Layout.scala#L286 because it doesn't take into account a possible path for `micrositeHomepage`.

**Comment by juanpedromoreno** [comment]
Weird, it doesn't work from https://typelevel.org/cats, but it's working fine for https://typelevel.org/cats/ (notice final slash). I guess the problem might be how Jekyll rewrite those urls/paths.

What do you think?

**Comment by BenFradet** [comment]
ah nice catch! Indeed that would be causing the issue, what do you reckon would solve the issue?

**Comment by juanpedromoreno** [comment]
Sadly, I don't know how to solve it :( . 

Any ideas how to solve this issue @calvellido ? Thanks.

**Comment by calvellido** [comment]
It looks like the URL gets formed by applying a partial route to the current one, probably looking for slash occurrences and working from the final one, hence not doing it alright when the main one doesn't rewrite the path by adding the final slash. The issue also happens on https://typelevel.org/scala

Yeah, maybe just a small regexp change could solve it, let me have a look (these days are a bit slow, though 🎅).

**Comment by juanpedromoreno** [comment]
:+1: thanks a lot @calvellido

**Comment by calvellido** [comment]
Hey @BenFradet, sorry for the lack of news, Christmas have been slow indeed 😅.

I was thinking about the best approach to take on this, and as the documentation states that the relative URL `micrositeDocumentationUrl` should be set as root-relative links, hence [the starting slash in the documentation example settings,](https://47deg.github.io/sbt-microsites/docs/settings.html#microsite-sbt-settings) I think the best way would be to change them on the Cats and Scala Typelevel projects settings.

An aggregation using `micrositeHomepage` and `micrositeDocumentationUrl` from the sbt-microsites side would also work, but that would mean change the initial grasp of those settings, and also could imply some undesired side-effects.

I proposed a couple of PRs to those projects, would you think that this would be ok to solve this issue?

**Comment by BenFradet** [comment]
Yup, thanks a bunch! 👍
