### ISSUE TITLE
Embedding meta tag for page title

### ISSUE THREAD

**Issue by xerial** [47deg/sbt-microsites#254]
Thanks for the great plugin, and I enjoy using sbt-microsites.

One pain point is in showing page titles. Is there any way to embed page title as metadata for facebook (og:title), twitter (twitter:title), etc? In the current version, the default page title is always used. 

For example, in the following page:
http://wvlet.org/airframe/docs/comparison.html
I expect showing the page title, _Airframe - DI Framework Comparison_ in the browser tab, but only _Airframe_ is shown.

**Comment by xerial** [comment]
Created a PR for addressing this issue #255.

**Comment by juanpedromoreno** [comment]
Solved by #255

**Comment by juanpedromoreno** [comment]
@xerial 0.7.15 version has been released with this feature.
