### ISSUE TITLE
upgrade to tut 0.6.3

### ISSUE THREAD

**Issue by BennyHill** [47deg/sbt-microsites#259]
`tut` 0.6.3  is [now released](https://github.com/tpolecat/tut/releases/tag/v0.6.3), please can this be updated so we can build/release cats for 2.13.0-M3, please

ref https://github.com/typelevel/cats/pull/2173

**Comment by eperinan** [comment]
Hi @BennyHill, thanks for your issue.

I have just created a PR to bump the version of this plugin https://github.com/47deg/sbt-org-policies to his last version. This version has the version that you need of `tut`.

**Comment by BennyHill** [comment]
@eperinan Wow, quick turnaround !! Many thanks :+1:

**Comment by eperinan** [comment]
Done. You have available the new version already https://github.com/47deg/sbt-microsites/releases/tag/v0.7.17

**Comment by BennyHill** [comment]
Thanks, I will have time to look a this Tuesday.
