### ISSUE TITLE
Add configuration so that the “Documentation”  is customizable on the top right corner on the homepage

### ISSUE THREAD

**Issue by Obarros** [47deg/sbt-microsites#267]
Make the description that appears on the top right corner to be something else and not “Documentation” when desired.

As of now the value that is showed is not customizable at the moment.
We are getting the string from:

https://github.com/47deg/sbt-microsites/blob/c06973586873c4addab34d1af08f1eef95c3a6d8/src/main/scala/microsites/layouts/Layout.scala#L290

Not a big deal, but we can use the same configuration logic for it.
I can try to submit a PR for it if it's something that you would like to see:
Any help or suggestions are much appreciated.

**Comment by calvellido** [comment]
Hi @Obarros, thanks for opening this, would be a a nice new feature indeed, PRs welcome of course!  If not, I can try or have a look at it end of this week or next.

I guess the best path to follow would be to base the behaviour of this on the way `micrositeDocumentationUrl` param, or other [microsite SBT settings](https://47deg.github.io/sbt-microsites/docs/settings.html) works. And to not break old sites in case they update to a `sbt-micrsosites` version including this new feature, I would set `'Documentation'` as the default value for this param.

You can find the keys being declared [around here](https://github.com/47deg/sbt-microsites/blob/master/src/main/scala/microsites/MicrositeKeys.scala), the default values can set [here](https://github.com/47deg/sbt-microsites/blob/master/src/main/scala/microsites/MicrositesPlugin.scala), and also you should probably add some arbitraries on [here](https://github.com/47deg/sbt-microsites/blob/master/src/test/scala/microsites/util/Arbitraries.scala).

If you start working on it and need further guidance don't hesitate to comment it on this issue, or in Gitter. Thanks!

**Comment by calvellido** [comment]
@Obarros thank you very much for your contribution!  Version `0.7.20` has been released including the feature to customize the Documentation label:

https://github.com/47deg/sbt-microsites/releases/tag/v0.7.20

**Comment by Obarros** [comment]
@calvellido Thanks for your valuable support! ;)
