### ISSUE TITLE
Support syntax highlighting for additional languages

### ISSUE THREAD

**Issue by thesamet** [47deg/sbt-microsites#275]
I'm trying to add an additional language (`protobuf`) to the syntax highlighter.

Currently, microsites supports only `scala`, `java` and `bash`. This is hard-coded in two places:

1. `highlight.pack.js` is pre-built with support only for these languages. 
2. https://github.com/47deg/sbt-microsites/blob/a7b51de6643a5b14c325e1b7f7b176a64d1dcf99/src/main/scala/microsites/layouts/Layout.scala#L213-L217

One way to go about (1) is to allow users to bring their own `highlight.pack.js`. Maybe it is possible now? I couldn't find any documentation on this. Another way about it is to create a setting that would `<script src>` additional languages from https://cdnjs.com/libraries/highlight.js/  . This can not be accomplished today with `CdnDirectives(jsList=...) since those scripts are sourced after `hljs.configure()` gets called.

For (2), we can add an SBT key for `micrositeHighlighterLanguages` that defaults to `Seq("scala", "java", "bash")` for backwards compatibility. The same key should probably control the additional languages to download from the CDN.

Thoughts? Happy to send over a PR.

**Comment by juanpedromoreno** [comment]
Thanks @thesamet , both options look good. Perhaps option 2 is more SBT/Scala friendly, in my opinion... And yes! any contribution is totally welcome :)
