### ISSUE TITLE
Change tut for mdoc

### ISSUE THREAD

**Issue by erikwj** [47deg/sbt-microsites#292]
Any thoughts about changing tut for mdoc. Anyone already looking at it?

**Comment by juanpedromoreno** [comment]
Yes, thanks for asking, we are already working on the support of mdoc.

**Comment by rafaparadela** [comment]
@erikwj We are working on supporting both `tut` and `mdoc`, putting special emphasis on preserving the compatibility with previous versions of the docs. Hopefully, we'll have a PR anytime soon, along with a guide to migrate smoothly.

**Comment by erikwj** [comment]
Great work folks. Good luck!
