### ISSUE TITLE
globalFooter takes GitHostingService type name instead of name

### ISSUE THREAD

**Issue by kczulko** [47deg/sbt-microsites#299]
When you set following sbt setting:
```
micrositeGitHostingService := Other("OtherSite")
```
global footer will display: `View on Other("OtherSite")` instead of `View on OtherSite` due to lack of `.gitHostingService.name` here:  
https://github.com/47deg/sbt-microsites/blob/9d56a23cf8d9a83a12c1c9da01260a55fc38d29d/src/main/scala/microsites/layouts/Layout.scala#L228

I'll try to fix it in my spare time and submit PR. If there is anyone that can do it faster than me, please don't hesitate.

Best regards,
Karol

**Comment by calvellido** [comment]
Ah, that would be great Karol. If you need help tackling it please ask around here, thanks!

**Comment by juanpedromoreno** [comment]
Closed by https://github.com/47deg/sbt-microsites/pull/300
