### ISSUE TITLE
[UI] Sometimes active doc page isn't highlighted within menu panel.

### ISSUE THREAD

**Issue by kczulko** [47deg/sbt-microsites#301]
Hi,

When I run sbt-microsites `Doc` section and when I choose some doc page from the left panel, sometimes it is not being highlighted as the active one. Please see the example below (taken from sbt-microsites microsite).

Here the `Layouts` menu is highlighted as the active one:
<img width="264" alt="layouts" src="https://user-images.githubusercontent.com/19495571/53397131-9a719480-39a6-11e9-8fb9-d398783994e0.PNG">

But here `Build the microsite` isn't:
<img width="393" alt="buildthemicrosite" src="https://user-images.githubusercontent.com/19495571/53397152-a8271a00-39a6-11e9-9fe9-24f9f2bed7e7.PNG">

If anyone could point me where I can fix that, I could try to handle it and submit PR.

Best regards,
Karol

**Comment by kczulko** [comment]
Hi,

I think I know what's the root cause of that...

Please take a look here:
https://github.com/47deg/sbt-microsites/blob/master/docs/src/main/resources/microsite/data/menu.yml#L17

The `title` here is `Build the microsite` which isn't exactly the same string that is defined here (layout section - **docs | Build the Microsite**)
https://github.com/47deg/sbt-microsites/blob/master/docs/src/main/tut/docs/build-the-microsite.md

If there is any discrepancy then there are issues with highlighting selected doc page.

Best regards,
Karol

**Comment by calvellido** [comment]
Hi @kczulko, the discrepancy on that specific case is the capitalization of `Microsite`. You can submit a PR for that setting the same value in both cases if you'd like to fix that in _sbt-microsites_ documentation.

Also, if you want to improve this feature in general, maybe you can normalize capitalization when the comparison happens, which is made in this template:

https://github.com/47deg/sbt-microsites/blob/master/src/main/scala/microsites/layouts/DocsLayout.scala

**Comment by calvellido** [comment]
Thanks for point it out BTW! :clap:
