### ISSUE TITLE
Support micrositeExtraMdFiles with mdoc

### ISSUE THREAD

**Issue by seldridge** [47deg/sbt-microsites#318]
I noticed that when switching from `tut` to `mdoc`, that the `micrositeExtraMdFiles` option doesn't seem to be supported. This manifests as the requested additional markdown not being copied and not showing up in the built site.

Taking a quick look at how [the extra markdown is built using `tut`](https://github.com/47deg/sbt-microsites/blob/master/src/main/scala/microsites/MicrositeKeys.scala#L255) it appears that this simply isn't being done for the `mdoc` backend. It would be great if this was in there and I think it would be pretty straightforward to either replicate the `tut` logic for `mdoc` or generalize both.

(No promises...) but if I have some free personal time, I can see about a PR. Anyway, thanks for a great project!

**Comment by rafaparadela** [comment]
I'll take a look at this. Thanks for reporting @seldridge
