### ISSUE TITLE
Sbt-microsite style redesign

### ISSUE THREAD

**Issue by AntonioMateoGomez** [47deg/sbt-microsites#334]
In order to update sbt-microsites we need to implement changes in the project to generate the sites with the new style provided by the design team by this issue https://github.com/47deg/47deg-marketing/issues/635

This is described in https://github.com/47deg/marlow/issues/234

**Comment by israelperezglez** [comment]
Good Job @AntonioMateoGomez , I add some comments:

- Links should have a :hover
- Could we pick another Theme for highlight.js?
- In the sidebar we could add a :hover in the li a
- #masthead .text-center doesn't work in responsive. ~width: 750px~ --> max-width: 750px
