### ISSUE TITLE
Migrating from 0.9.7 to 1.x.x with "pattern" style yields no css directory

### ISSUE THREAD

**Issue by blast-hardcheese** [47deg/sbt-microsites#406]
Since the upgrade, it seems as though the `css` directory is completely missing, with the impact being that https://guardrail.dev/ is rendered completely without CSS.

The settings are here: https://github.com/twilio/guardrail/blob/master/modules/microsite/build.sbt
The build output is here: https://api.travis-ci.com/v3/job/267934501/log.txt

One potentially interesting aspect to this puzzle is that if I `publishMicrosite` locally, the CSS is correctly uploaded.

Any tips for debugging this?
Thank you for what you've provided!

**Comment by blast-hardcheese** [comment]
To fix the website, I ended up running `microsite/publishMicrosite` locally on my laptop, but that was immediately after running a release and having the CSS not end up in the published site.

**Comment by blast-hardcheese** [comment]
Turns out this is because I had not upgraded the versions of Ruby deps in `.travis.yml`:

```diff
-  - rvm use 2.3.0 --install --fuzzy
+  - rvm use 2.6.0 --install --fuzzy
   - gem update --system
   - gem install sass
-  - gem install jekyll -v 3.2.1
+  - gem install jekyll -v 4.0.0
```

Hopefully this'll help others if they run into this issue.

Thanks again!

**Comment by cb372** [comment]
I ran into exactly the same issue a few days ago with one of my projects. I'm going to make a PR now to add a Troubleshooting page to the docs on the microsite.
