### ISSUE TITLE
NoSuchMethodError: JsonFormat upon makeMicrosite

### ISSUE THREAD

**Issue by anthony-cros** [47deg/sbt-microsites#421]
Getting cryptic error `java.lang.NoSuchMethodError: sbt.package$.singleFileJsonFormatter()Lsjsonnew/JsonFormat` when trying out sbt-microsites:

```
$ scala -version
Scala code runner version 2.12.8 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc.

$ cat project/plugins.sbt 
addSbtPlugin("com.47deg"  % "sbt-microsites" % "1.1.0")

$ cat build.sbt 
name := "foo-docs"
scalaVersion := "2.12.8"
enablePlugins(MicrositesPlugin)

$ ~/bin/sbt/1_3_8/bin/sbt makeMicrosite
[info] Loading settings from plugins.sbt ...
[info] Loading global plugins from /home/tony/.sbt/1.0/plugins
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/tony/tmp/sbt-microsites/project
[error] java.lang.NoSuchMethodError: sbt.package$.singleFileJsonFormatter()Lsjsonnew/JsonFormat;
[error] 	at microsites.MicrositeKeys.$init$(MicrositeKeys.scala:120)
	...
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchMethodError: sbt.package$.singleFileJsonFormatter()Lsjsonnew/JsonFormat;
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

It seems to relate to this [error](https://github.com/sbt/sbt/issues/5049), but I'm unsure how the proposed solution applies here

**Comment by AntonioMateoGomez** [comment]
Hello @anthony-cros ! I think I can see what is happenig, you need to upgrade the `sbt.version` at least to the `1.3.0` in both files: 

`project/build.properties`
`src/sbt-test/a/b/project/build.properties`

In our own project we are using the `1.3.4` sbt version.

I hope it works!!

**Comment by anthony-cros** [comment]
Thanks a lot @AntonioMateoGomez for getting back to me on this.

Making the change for `project/build.properties` seem to have sufficed, although for reference to others I also had to add the following at the root for it to run successfully:

```
mkdir docs
echo 'hello _world_' > docs/hello.md
```
