### ISSUE TITLE
Manually configuring Jekyll

### ISSUE THREAD

**Issue by larsrh** [47deg/sbt-microsites#43]
I found the code block which [creates the Jekyll configuration](https://github.com/47deg/sbt-microsites/blob/6f3517acd6256a004d80f4f81e0b42fdba9cd698/src/main/scala/microsites/util/MicrositeHelper.scala#L55-L76). Would it be possible to take one from, let's say, `src/main/resources/microsite/` if it exists?

The reason I looked at this is because of slight rendering problems in typelevel/scala#117 which I believe come from a missing Kramdown configuration option (`input: GFM`).

**Comment by juanpedromoreno** [comment]
Fixed by #110
