### ISSUE TITLE
Delayed loading of styles

### ISSUE THREAD

**Issue by justinelsberry** [47deg/sbt-microsites#47]
When visiting a microsite, often the styles take a long time to load so you see the page without style for a second or so before the styled version loads.

For me, this can be seen on both these sites:
https://47deg.github.io/scalacheck-datetime/
https://47deg.github.io/fetch/

![2016-09-27 16_19_02](https://cloud.githubusercontent.com/assets/205617/18895390/1f6a00b8-84ce-11e6-84c0-fad034fd4b6a.gif)

**Comment by justinelsberry** [comment]
I see that those 2 sites mentioned may not have used the sbt-microsites plugin as the styles are loaded differently than on https://47deg.github.io/sbt-microsites/. The style is loaded in javascript so its deferred until after the page is loaded. @juanpedromoreno should we create tickets to upgrade those projects to use this version?

**Comment by rafaparadela** [comment]
Yes. Fetch, Mvessel and Github4s are using the previous version of
Microsite.

I would suggest that Alex, Fede and myself to spend some minutes to move it
into the new version based on the plugin.

I'd also recommend removing the repo "microsites" since is not longer
available.

**Comment by juanpedromoreno** [comment]
Closing this issue since all the mentioned projects here (using the old microsites project) are now using the sbt-microsites plugin.
