### ISSUE TITLE
Kazari plugin minimization

### ISSUE THREAD

**Issue by jdesiloniz** [47deg/sbt-microsites#62]
Currently the size of the resulting plugin after executing fullOptJS and merging it with the JS dependencies script is almost 1.5 MB. As soon as the plugin is in a stable state we should look into ways of reducing its size (i.e.: searching for an alternative to using Futures - as including ExecutionContexts seems to beef up the script by ~500KB) and maybe process the script with further optimizations/minimization processes after it's already generated as part of the fullOptGenerate task.

**Comment by juanpedromoreno** [comment]
Kazari has been removed from the project, we can close this.
