### ISSUE TITLE
Support multiple project versions

### ISSUE THREAD

**Issue by raulraja** [47deg/sbt-microsites#67]
We can use the repo tags/releases to allow publishing of multiple microsites, one for each version.
Not sure how much work would be involved in this since we would need to compile each one of those versions so potentially we would need isolated copies and move to those commits to generate the site while keeping the latest config active. Ideas on how to achieve this are welcome. We already have use cases where folks are requesting this feature https://github.com/typelevel/cats/pull/1369#issuecomment-246189985

**Comment by juanpedromoreno** [comment]
Not sure if this project https://github.com/epoberezkin/gh-pages-generator is the way to go.

**Comment by calvellido** [comment]
Superseded by #116
