### ISSUE TITLE
Scala Code is not properly Highlighted

### ISSUE THREAD

**Issue by juanpedromoreno** [47deg/sbt-microsites#70]
Scala Code not always is being well-displayed. Rob Norris has provided useful feedback around this issue. Here a couple of examples with different hightlight themes (`default` and `color-brewer`):

![1](https://cloud.githubusercontent.com/assets/4879373/19683958/f904017e-9ab4-11e6-8e18-1ded6854ee13.png)
![2](https://cloud.githubusercontent.com/assets/4879373/19683960/fc11e598-9ab4-11e6-956f-f3a51207f6f2.png)

As you can see, the comment starting with `// guessing loop with …` is not well-interpreted since the keyword `with` is being highlihted, and it shouldn't.

CC @tpolecat

**Comment by tpolecat** [comment]
Related, non-code blocks are being highlighted. Maybe it's trying to auto-detect the language or something?

![image](https://cloud.githubusercontent.com/assets/1200131/19684181/34b1ea34-9a8c-11e6-8db0-181a9a5e797d.png)

**Comment by tpolecat** [comment]
Ok I made my repo public. https://github.com/tpolecat/tuco … `modules/doc` is where the source is. Follow the link from the README to the published site. Thanks!
