### ISSUE TITLE
Allow user to provide Liquid variables via sbt

### ISSUE THREAD

**Issue by tpolecat** [47deg/sbt-microsites#72]
It would be nice if I could say something like

```
micrositeVariables := Map(
  "version" -> version.value,
  "org"     -> organization.value
)
```

or something like this, and push them forward into Jekyll so that I could say `{{microsite.version}}` in my markdown … keeping versions correct in doc is always a problem. A good default map might include version, name, description, and org.

You may have something like this in mind already. If not maybe I can hack it up? wdyt?

**Comment by juanpedromoreno** [comment]
Sounds good. Thanks!

We have to make a decision around this, Lars commented a different alternative: providing the ability to create your own jekyll configuration and put it as a resource: https://github.com/47deg/sbt-microsites/issues/43

**Comment by juanjovazquez** [comment]
This is very useful and is present in other tools like [Paradox](http://developer.lightbend.com/docs/paradox/latest/) through the `@var` directive and the `paradoxProperties` setting. I'd rather not to leave SBT to configure these properties.
