### ISSUE TITLE
Enable anchor links

### ISSUE THREAD

**Issue by raulraja** [47deg/sbt-microsites#74]
Existing generated pages don't link to anchor links generated from `#` blocks.

**Comment by raulraja** [comment]
Let's fix this as part of the 47 site overhaul.

**Comment by calvellido** [comment]
Hi! So apparently, the current implementation  of the markdown parser already supports anchor links. The parser creates id for all titles in a page/article, e.g. given this article:

https://www.47deg.com/blog/what-we-learned-organizing-conferences/

We can already link to an specific title present in the post, for example [How does and event start](https://www.47deg.com/blog/what-we-learned-organizing-conferences/#how-does-an-event-start). To do it inside the article, we can just use a syntax like this:

`Go to section [How does an event start](#how-does-an-event-start)`

**Comment by raulraja** [comment]
The issue is that headers are not auto linked. so the following markdown:
```md
# Whatever
```
Does not get a link that can be used when sharing nested sections.
see for example http://frees.io/docs/core/algebras/ where sections are not linked to their own anchor.

**Comment by calvellido** [comment]
Indeed they are, to get an anchor to any header on the documentation you can convert any of them (`# ## ###`) to a kebab-case styled link to refer to its autogenerated id. By using a proper `sbt-microsites` example, like the [frees.io](http://frees.io) page:

`## Convenient type aliases`

This subsection from the [Algebras](http://frees.io/docs/core/algebras/) section, can be linked by a Markdown code like this:

`There's a section to read more about type aliases, please refer to [convenient type aliases](#covenient-type-aliases)`

This can be done in the same page. But you can even link to subsections, from into another section. For example, being in the Algebras section and wanting to link to Modules -> Dependency injection subsection you can do it appending the anchor link to the referral.

`Fear not. Freestyle provides a [modular system](../modules#dependency-injection)`


Maybe I'm misleading the issue, and its intention is to provide some automatization or something?

**Comment by calvellido** [comment]
The ideal implementation would be to have something like the current behaviour of headings on Github pages and/or Github issues and parsed READMEs. This is a small _linkified_ button element that appears on hover on each heading.

Considering this, and that we already generate HTML ids from Markdown headers, a JS implementation is something quick, and will be the proposed solution.

**Comment by calvellido** [comment]
Included solution will show something like this:

![captura de pantalla de 2017-12-01 16-18-53](https://user-images.githubusercontent.com/7753447/33489325-dbc49a1a-d6b3-11e7-82c8-7b0471b3c6d5.png)
