### ISSUE TITLE
table formatting is slightly wack

### ISSUE THREAD

**Issue by tpolecat** [47deg/sbt-microsites#76]
The default styling doesn't paint borders around tables, which makes them slightly strange looking.

![image](https://cloud.githubusercontent.com/assets/1200131/19830130/70ce76f2-9dc7-11e6-862f-5d8d155211af.png)

What I would really like I think is an option that makes formatting _exactly_ like what GH does, if that's an easy thing to do (no idea).

**Comment by jvican** [comment]
:+1:
