### ISSUE TITLE
gitter link in header?

### ISSUE THREAD

**Issue by tpolecat** [47deg/sbt-microsites#77]
Might be nice to gen a link to gitter up in the header since it's pretty standard these days.

**Comment by rafaparadela** [comment]
Yes! We are planning to implement a better integration with Gitter. Not
only with a link in header, but also a embedded sidebar with the channel
(called Gitter Sidecar). I guess the issues have been created.

**Comment by juanpedromoreno** [comment]
Fixed in https://github.com/47deg/sbt-microsites/pull/183
