### ISSUE TITLE
Allow custom javascript in generated microsite

### ISSUE THREAD

**Issue by sritchie** [47deg/sbt-microsites#84]
Hey all,

I'm looking to include a mathjax js import in the microsite for Algebird (twitter.github.io/algebird), but it doesn't look like I can inject this into a page template at the moment. Am I missing something? If not, would it be possible to create a new key for the sbt plugin that accepts a list of JS libraries to load?

Thanks!

**Comment by juanpedromoreno** [comment]
Fixed with #86

**Comment by sritchie-stripe** [comment]
Thank you @juanpedromoreno! Totally happy to make changes via PR in the future, but with a request like this I really appreciate your guidance so the design stays consistent.

**Comment by juanpedromoreno** [comment]
Re-opened: 

We should include the capability to include JS from a CDN
