### ISSUE TITLE
Add `Edit Page` feature to any page

### ISSUE THREAD

**Issue by raulraja** [47deg/sbt-microsites#96]
Users should be able to edit pages directly by providing links to either Github or other VCS as configured via settings to go to actual sources on each one of the generated pages.

This will allow lib maintainers to get easy low hanging fruit style contribs from their users to increase lib engagement.

**Comment by raulraja** [comment]
This should also be an opt out feature that may be disabled but enabled by default.

**Comment by sritchie** [comment]
I've been doing this manually, and would love if we had a built-in option for this.

**Comment by britneywright** [comment]
@juanpedromoreno I know my PR #278 that was merged was only scoped to the documentation layout pages. Not sure if this issue should be amended or closed.

**Comment by calvellido** [comment]
I think that exactly was the goal of this issue, so IMO it can be closed, but will let that decision to @juanpedromoreno 

Thanks again @britneywright, great contribution! :+1:

**Comment by juanpedromoreno** [comment]
Yes, I also think this issue can be closed :)

Thanks!
