### ISSUE TITLE
Add documentation to publish microsites with travis

### ISSUE THREAD

**Issue by julien-truffaut** [47deg/sbt-microsites#98]

**Comment by jonas** [comment]
I plan to document document this for sbt-site using sbt-ghpages based on [this](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd) approach.

**Comment by jonas** [comment]
The documentation can be found here: http://www.scala-sbt.org/sbt-site/publishing.html#publishing-to-github-pages-from-travis-ci

Suggestions and improvements welcome.

**Comment by javipacheco** [comment]
We have added the documentation here: https://47deg.github.io/sbt-microsites/docs/publish-with-travis.html

:+1:

**Comment by julien-truffaut** [comment]
Awesome, thank you!
